server:
  port: 8080

# dev env
spring:
  profiles:
    activate:
      on-profile: dev

  application:
    name: transaction-demo
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    driver-class-name: org.h2.Driver
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:pwd123}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:validate}
    show-sql: ${DB_SHOW_SQL:true}
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

logging:
  level:
    root: INFO
    com.demo: DEBUG
  file:
    name: dev.log